---

name: Publish Version
on:
  release:
    types: [created, edited]
jobs:
  publish:
    name: Publish Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch Tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* || true
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.REGION }}
      - name: Set version
        id: version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      # Setup
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install python dependencies
        run: pip3 install awscli
      # Package and Upload Archive
      - name: Create Archive
        run: git archive HEAD -o $VERSION.zip
      - name: Upload artefact
        run: aws s3 cp ./$VERSION.zip s3://$CFN_BUCKET/aws-decoupled-serverless-scheduler/$VERSION/aws-decoupled-serverless-scheduler.zip >/dev/null 2>&1
        env:
          CFN_BUCKET: ${{ secrets.CFN_BUCKET }}
